#!/bin/sh

# central configuration for calls into different subsystems.

base=`dirname "$0"`
command="$1"
shift

case $command in

	initscript)	exec $base/php/admin/rira.initscript	"$@" ;;
	searchindex)	exec $base/php/admin/searchindex.php	"$@" ;;

	search)		exec $base/lucene-java/search		"$@" ;;
	makeindex)	exec $base/lucene-java/makeindex	"$@" ;;

esac
