#!/bin/sh



base=`dirname "$0"`
JAVA=java
INDEX="$base/index"

test -f "$base/config" && . "$base/config"


rm -rf "${INDEX}new"

$base/../config searchindex |
$base/classpath $JAVA ir.rira.search.IndexObjects "${INDEX}new" > "${INDEX}log" &&
chmod a+w "${INDEX}new" &&
( test -f "${INDEX}" && mv "${INDEX}" "${INDEX}old" || : ) &&
mv "${INDEX}new" "${INDEX}" &&
rm -rf "${INDEX}old"
